{"events":[

],
"damage":[
{ "id": 1, "msg": "-OTPC- Richard_Ticklah (Do 335 B) уничтожил Артиллерия", "sender": "", "enemy": false, "mode": "" },
{ "id": 2, "msg": "-OTPC- Richard_Ticklah (Do 335 B) ударил первым!", "sender": "", "enemy": false, "mode": "" },
{ "id": 3, "msg": "-OTPC- Richard_Ticklah (Do 335 B) уничтожил Артиллерия", "sender": "", "enemy": false, "mode": "" },
{ "id": 4, "msg": "-OTPC- Richard_Ticklah (Do 335 B) уничтожил ПВО", "sender": "", "enemy": false, "mode": "" },
{ "id": 5, "msg": "-OTPC- Richard_Ticklah (Do 335 B) получил \"Тройной удар!\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 6, "msg": "-OTPC- Richard_Ticklah (Do 335 B) уничтожил ПВО", "sender": "", "enemy": false, "mode": "" },
{ "id": 7, "msg": "Ndfeb (Do 335 B) уничтожил Лёгкий ДОТ", "sender": "", "enemy": false, "mode": "" },
{ "id": 8, "msg": "-OTPC- Richard_Ticklah (Do 335 B) уничтожил ПВО", "sender": "", "enemy": false, "mode": "" },
{ "id": 9, "msg": "-OTPC- Richard_Ticklah (Do 335 B) подбил HOGHEAD22791 (AM-1)", "sender": "", "enemy": false, "mode": "" },
{ "id": 10, "msg": "Ndfeb (Do 335 B) подбил HOGHEAD22791 (AM-1)", "sender": "", "enemy": false, "mode": "" },
{ "id": 11, "msg": "-Reply- Just4History (Do 335 B) уничтожил Артиллерия", "sender": "", "enemy": false, "mode": "" },
{ "id": 12, "msg": "HOGHEAD22791 (AM-1) уничтожил ПВО", "sender": "", "enemy": false, "mode": "" },
{ "id": 13, "msg": "HOGHEAD22791 (AM-1) уничтожил Лёгкий ДОТ", "sender": "", "enemy": false, "mode": "" },
{ "id": 14, "msg": "-OTPC- Richard_Ticklah (Do 335 B) сбил HOGHEAD22791 (AM-1)", "sender": "", "enemy": false, "mode": "" },
{ "id": 15, "msg": "Ndfeb (Do 335 B) сбил ⋇KevinKing12347 (AM-1)", "sender": "", "enemy": false, "mode": "" },
{ "id": 16, "msg": "⋇KevinKing12347 (AM-1) сбил Ndfeb (Do 335 B)", "sender": "", "enemy": false, "mode": "" },
{ "id": 17, "msg": "-OTPC- Richard_Ticklah (Do 335 B) уничтожил ПВО", "sender": "", "enemy": false, "mode": "" },
{ "id": 18, "msg": "⋇KevinKing12347 (AM-1) поджёг Ndfeb (Do 335 B)", "sender": "", "enemy": false, "mode": "" },
{ "id": 19, "msg": "-OTPC- Richard_Ticklah (Do 335 B) уничтожил Артиллерия", "sender": "", "enemy": false, "mode": "" },
{ "id": 20, "msg": "HOGHEAD22791 потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 21, "msg": "HOGHEAD22791td! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 22, "msg": "-Reply- Just4History (Do 335 B) уничтожил Артиллерия", "sender": "", "enemy": false, "mode": "" },
{ "id": 23, "msg": "-Reply- Just4History (Do 335 B) уничтожил Артиллерия", "sender": "", "enemy": false, "mode": "" },
{ "id": 24, "msg": "⋇KevinKing12347 потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 25, "msg": "⋇KevinKing12347td! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 26, "msg": "Ndfeb потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 27, "msg": "Ndfebtd! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 28, "msg": "*286* ⋇xPIGEONxTOEx (AD-2) уничтожил Брандер", "sender": "", "enemy": false, "mode": "" },
{ "id": 29, "msg": "┾AURI┿ M2UWUWU (F2G-1) уничтожил Брандер", "sender": "", "enemy": false, "mode": "" },
{ "id": 30, "msg": "*286* ⋇xPIGEONxTOEx (AD-2) уничтожил Брандер", "sender": "", "enemy": false, "mode": "" },
{ "id": 31, "msg": "┾AURI┿ M2UWUWU (F2G-1) уничтожил Брандер", "sender": "", "enemy": false, "mode": "" },
{ "id": 32, "msg": "*286* ⋇xPIGEONxTOEx (AD-2) уничтожил Брандер", "sender": "", "enemy": false, "mode": "" },
{ "id": 33, "msg": "┾AURI┿ M2UWUWU (F2G-1) уничтожил Брандер", "sender": "", "enemy": false, "mode": "" },
{ "id": 34, "msg": "┾AURI┿ M2UWUWU (F2G-1) уничтожил Брандер", "sender": "", "enemy": false, "mode": "" },
{ "id": 35, "msg": "┾AURI┿ M2UWUWU (F2G-1) уничтожил Брандер", "sender": "", "enemy": false, "mode": "" },
{ "id": 36, "msg": "┾AURI┿ M2UWUWU (F2G-1) уничтожил Брандер", "sender": "", "enemy": false, "mode": "" },
{ "id": 37, "msg": "*286* ⋇xPIGEONxTOEx (AD-2) уничтожил Брандер", "sender": "", "enemy": false, "mode": "" },
{ "id": 38, "msg": "mr5string96 (Fw 190 A) поджёг *286* ⋇xPIGEONxTOEx (AD-2)", "sender": "", "enemy": false, "mode": "" },
{ "id": 39, "msg": "mr5string96 (Fw 190 A) сбил *286* ⋇xPIGEONxTOEx (AD-2)", "sender": "", "enemy": false, "mode": "" },
{ "id": 40, "msg": "mr5string96 (Fw 190 A) получил \"Спасатель водной техники\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 41, "msg": "┾AURI┿ M2UWUWU (F2G-1) подбил mr5string96 (Fw 190 A)", "sender": "", "enemy": false, "mode": "" },
{ "id": 42, "msg": "┾AURI┿ M2UWUWU (F2G-1) сбил mr5string96 (Fw 190 A)", "sender": "", "enemy": false, "mode": "" },
{ "id": 43, "msg": "*286* ⋇xPIGEONxTOEx потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 44, "msg": "⋇xPIGEONxTOExtd! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 45, "msg": "-Reply- Just4History (Do 335 B) подбил ┾AURI┿ M2UWUWU (F2G-1)", "sender": "", "enemy": false, "mode": "" },
{ "id": 46, "msg": "mr5string96 потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 47, "msg": "mr5string96td! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 48, "msg": "dobby196 (Bf 109 K) разбился", "sender": "", "enemy": false, "mode": "" },
{ "id": 49, "msg": "-Reply- Just4History (Do 335 B) сбил ┾AURI┿ M2UWUWU (F2G-1)", "sender": "", "enemy": false, "mode": "" },
{ "id": 50, "msg": "-Reply- Just4History (Do 335 B) получил \"Спасатель водной техники\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 51, "msg": "dobby196 потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 52, "msg": "dobby196td! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 53, "msg": "=FEAC= ⋇Turny Dragon (Seafire Mk.III) подбил -OTPC- Richard_Ticklah (Do 335 B)", "sender": "", "enemy": false, "mode": "" },
{ "id": 54, "msg": "=GMCM= EinSchnitzel (Ju 288 C) поджёг =GMCM= _Razerm_ (Ju 288 C)", "sender": "", "enemy": false, "mode": "" },
{ "id": 55, "msg": "=FEAC= ⋇Turny Dragon (Seafire Mk.III) поджёг -OTPC- Richard_Ticklah (Do 335 B)", "sender": "", "enemy": false, "mode": "" },
{ "id": 56, "msg": "┾AURI┿ M2UWUWU потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 57, "msg": "M2UWUWUtd! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 58, "msg": "=GMCM= _Razerm_ (Ju 288 C) подбил =GMCM= EinSchnitzel (Ju 288 C)", "sender": "", "enemy": false, "mode": "" },
{ "id": 59, "msg": "=GMCM= _Razerm_ (Ju 288 C) поджёг =GMCM= EinSchnitzel (Ju 288 C)", "sender": "", "enemy": false, "mode": "" },
{ "id": 60, "msg": "=RdLS= ⋇Name is Jeff332 (Re.2005 serie 0) сбил =FEAC= ⋇Turny Dragon (Seafire Mk.III)", "sender": "", "enemy": false, "mode": "" },
{ "id": 61, "msg": "-Reply- Just4History (Do 335 B) подбил ⋇JAY505 (F4U-4)", "sender": "", "enemy": false, "mode": "" },
{ "id": 62, "msg": "-Reply- Just4History (Do 335 B) сбил ⋇JAY505 (F4U-4)", "sender": "", "enemy": false, "mode": "" },
{ "id": 63, "msg": "-Reply- Just4History (Do 335 B) получил \"Двойной удар!\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 64, "msg": "-Reply- Just4History (Do 335 B) поджёг ⋇JAY505 (F4U-4)", "sender": "", "enemy": false, "mode": "" },
{ "id": 65, "msg": "blyaat123 (▄Bf.109G) подбил [thiqe] KomradeYuri (Spitfire)", "sender": "", "enemy": false, "mode": "" },
{ "id": 66, "msg": "[thiqe] KomradeYuri (Spitfire) подбил -OTPC- Richard_Ticklah (Do 335 B)", "sender": "", "enemy": false, "mode": "" },
{ "id": 67, "msg": "[thiqe] KomradeYuri (Spitfire) поджёг -OTPC- Richard_Ticklah (Do 335 B)", "sender": "", "enemy": false, "mode": "" },
{ "id": 68, "msg": "=GMCM= EinSchnitzel (Ju 288 C) сбил =GMCM= _Razerm_ (Ju 288 C)", "sender": "", "enemy": false, "mode": "" },
{ "id": 69, "msg": "blyaat123 (▄Bf.109G) сбил [thiqe] KomradeYuri (Spitfire)", "sender": "", "enemy": false, "mode": "" },
{ "id": 70, "msg": "[thiqe] KomradeYuri (Spitfire) сбил -OTPC- Richard_Ticklah (Do 335 B)", "sender": "", "enemy": false, "mode": "" },
{ "id": 71, "msg": "-OTPC- Richard_Ticklah потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 72, "msg": "Richard_Ticklahtd! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 73, "msg": "⋇JAY505 потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 74, "msg": "⋇JAY505td! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 75, "msg": "[thiqe] KomradeYuri потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 76, "msg": "KomradeYuritd! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 77, "msg": "=FEAC= ⋇Turny Dragon потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 78, "msg": "⋇Turny Dragontd! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 79, "msg": "=GMCM= _Razerm_ (Ju 288 C) сбил =GMCM= EinSchnitzel (Ju 288 C)", "sender": "", "enemy": false, "mode": "" },
{ "id": 80, "msg": "=GMCM= EinSchnitzel потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 81, "msg": "EinSchnitzeltd! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 82, "msg": "=GMCM= _Razerm_ потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 83, "msg": "_Razerm_td! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 84, "msg": "ПВО сбил =BFLOP= Killakony (▃Spitfire)", "sender": "", "enemy": false, "mode": "" },
{ "id": 85, "msg": "MurrayP47 (Fw 190 D) подбил =HHC= ⋇Maddogz24 (PB4Y-2)", "sender": "", "enemy": false, "mode": "" },
{ "id": 86, "msg": "MurrayP47 (Fw 190 D) поджёг =HHC= ⋇Maddogz24 (PB4Y-2)", "sender": "", "enemy": false, "mode": "" },
{ "id": 87, "msg": "MurrayP47 (Fw 190 D) сбил =HHC= ⋇Maddogz24 (PB4Y-2)", "sender": "", "enemy": false, "mode": "" },
{ "id": 88, "msg": "blyaat123 (▄Bf.109G) уничтожил Автотранспорт", "sender": "", "enemy": false, "mode": "" },
{ "id": 89, "msg": "blyaat123 (▄Bf.109G) уничтожил Автотранспорт", "sender": "", "enemy": false, "mode": "" },
{ "id": 90, "msg": "blyaat123 (▄Bf.109G) уничтожил Автотранспорт", "sender": "", "enemy": false, "mode": "" },
{ "id": 91, "msg": "blyaat123 (▄Bf.109G) получил \"Тройной удар!\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 92, "msg": "blyaat123 (▄Bf.109G) уничтожил Автотранспорт", "sender": "", "enemy": false, "mode": "" },
{ "id": 93, "msg": "blyaat123 (▄Bf.109G) получил \"Наземный Мультиудар x4!\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 94, "msg": "blyaat123 (▄Bf.109G) уничтожил Автотранспорт", "sender": "", "enemy": false, "mode": "" },
{ "id": 95, "msg": "blyaat123 (▄Bf.109G) получил \"Наземный Мультиудар x5!\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 96, "msg": "-K21- skyraider7438213 (B-17G) сбил MurrayP47 (Fw 190 D)", "sender": "", "enemy": false, "mode": "" },
{ "id": 97, "msg": "blyaat123 (▄Bf.109G) уничтожил Артиллерия", "sender": "", "enemy": false, "mode": "" },
{ "id": 98, "msg": "=BFLOP= Killakony потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 99, "msg": "Killakonytd! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 100, "msg": "blyaat123 (▄Bf.109G) уничтожил Артиллерия", "sender": "", "enemy": false, "mode": "" },
{ "id": 101, "msg": "blyaat123 (▄Bf.109G) уничтожил Автотранспорт", "sender": "", "enemy": false, "mode": "" },
{ "id": 102, "msg": "MurrayP47 потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 103, "msg": "MurrayP47td! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 104, "msg": "blyaat123 (▄Bf.109G) уничтожил Артиллерия", "sender": "", "enemy": false, "mode": "" },
{ "id": 105, "msg": "blyaat123 (▄Bf.109G) уничтожил Артиллерия", "sender": "", "enemy": false, "mode": "" },
{ "id": 106, "msg": "=HHC= ⋇Maddogz24 потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 107, "msg": "⋇Maddogz24td! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 108, "msg": "blyaat123 (▄Bf.109G) уничтожил Артиллерия", "sender": "", "enemy": false, "mode": "" },
{ "id": 109, "msg": "blyaat123 (▄Bf.109G) уничтожил Артиллерия", "sender": "", "enemy": false, "mode": "" },
{ "id": 110, "msg": "-Watty- KingFlippyNipps (B-17G) поджёг =RdLS= ⋇Name is Jeff332 (Re.2005 serie 0)", "sender": "", "enemy": false, "mode": "" },
{ "id": 111, "msg": "=RdLS= ⋇Name is Jeff332 (Re.2005 serie 0) подбил -Watty- KingFlippyNipps (B-17G)", "sender": "", "enemy": false, "mode": "" },
{ "id": 112, "msg": "=RdLS= ⋇Name is Jeff332 (Re.2005 serie 0) поджёг -Watty- KingFlippyNipps (B-17G)", "sender": "", "enemy": false, "mode": "" },
{ "id": 113, "msg": "blyaat123 (▄Bf.109G) уничтожил Автотранспорт", "sender": "", "enemy": false, "mode": "" },
{ "id": 114, "msg": "-Watty- KingFlippyNipps (B-17G) сбил =RdLS= ⋇Name is Jeff332 (Re.2005 serie 0)", "sender": "", "enemy": false, "mode": "" },
{ "id": 115, "msg": "blyaat123 (▄Bf.109G) уничтожил Артиллерия", "sender": "", "enemy": false, "mode": "" },
{ "id": 116, "msg": "=RdLS= ⋇Name is Jeff332 (Re.2005 serie 0) сбил -Watty- KingFlippyNipps (B-17G)", "sender": "", "enemy": false, "mode": "" },
{ "id": 117, "msg": "=RdLS= ⋇Name is Jeff332 (Re.2005 serie 0) получил \"Око за око\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 118, "msg": "blyaat123 (▄Bf.109G) уничтожил Артиллерия", "sender": "", "enemy": false, "mode": "" },
{ "id": 119, "msg": "=RdLS= ⋇Name is Jeff332 потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 120, "msg": "⋇Name is Jeff332td! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 121, "msg": "blyaat123 (▄Bf.109G) уничтожил Артиллерия", "sender": "", "enemy": false, "mode": "" },
{ "id": 122, "msg": "-Watty- KingFlippyNipps потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 123, "msg": "KingFlippyNippstd! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 124, "msg": "BushWoookie (Ju 288 C) разбился", "sender": "", "enemy": false, "mode": "" },
{ "id": 125, "msg": "BushWoookie потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 126, "msg": "BushWoookietd! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 127, "msg": "blyaat123 (▄Bf.109G) уничтожил Автотранспорт", "sender": "", "enemy": false, "mode": "" },
{ "id": 128, "msg": "blyaat123 (▄Bf.109G) уничтожил Артиллерия", "sender": "", "enemy": false, "mode": "" },
{ "id": 129, "msg": "-K21- skyraider7438213 (B-17G) разбился", "sender": "", "enemy": false, "mode": "" },
{ "id": 130, "msg": "-K21- skyraider7438213 потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 131, "msg": "skyraider7438213td! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 132, "msg": "blyaat123 (▄Bf.109G) уничтожил Артиллерия", "sender": "", "enemy": false, "mode": "" },
{ "id": 133, "msg": "blyaat123 (▄Bf.109G) уничтожил Артиллерия", "sender": "", "enemy": false, "mode": "" },
{ "id": 134, "msg": "blyaat123 (▄Bf.109G) уничтожил ПВО", "sender": "", "enemy": false, "mode": "" },
{ "id": 135, "msg": "[SICH] _Strepsils_ (Me 264) подбил ⋇PERP3TUALSCUM (B-17G)", "sender": "", "enemy": false, "mode": "" },
{ "id": 136, "msg": "[SICH] _Strepsils_ (Me 264) сбил ⋇PERP3TUALSCUM (B-17G)", "sender": "", "enemy": false, "mode": "" },
{ "id": 137, "msg": "[SICH] _Strepsils_ (Me 264) получил \"Сюрприз!\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 138, "msg": "Ndfeb (Do 335 B) получил \"На подхвате\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 139, "msg": "[SICH] _Strepsils_ (Me 264) нанёс последний удар!", "sender": "", "enemy": false, "mode": "" },
{ "id": 140, "msg": "┾AURI┿ M2UWUWU (F2G-1) получил \"Девятый вал\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 141, "msg": "blyaat123 (▄Bf.109G) получил \"Громовержец\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 142, "msg": "-Reply- Just4History (Do 335 B) получил \"Гроза небес\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 143, "msg": "-Reply- Just4History (Do 335 B) получил \"Пуленепробиваемый\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 144, "msg": "⋇PERP3TUALSCUM потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 145, "msg": "⋇PERP3TUALSCUMtd! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 146, "msg": "-Reply- Just4History потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 147, "msg": "Just4Historytd! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" }
]}

{"events":[

],
"damage":[
{ "id": 193, "msg": "*MXG* fidler21 (F4U-4) подбил ^OM2GD^ Catzo_ (Ту-2С)", "sender": "", "enemy": false, "mode": "" },
{ "id": 194, "msg": "*MXG* fidler21 (F4U-4) сбил ^OM2GD^ Catzo_ (Ту-2С)", "sender": "", "enemy": false, "mode": "" },
{ "id": 195, "msg": "*MXG* fidler21 (F4U-4) сбил ^OM2GD^ Old_Man1820 (Fw 190 F)", "sender": "", "enemy": false, "mode": "" },
{ "id": 196, "msg": "⋇Lucid_Cribzz100 (A-26C) уничтожил Гаубица", "sender": "", "enemy": false, "mode": "" },
{ "id": 197, "msg": "^OM2GD^ Catzo_ потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 198, "msg": "Catzo_td! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 199, "msg": "CaptainCaribou (Як-3) поджёг =SKG10= FolyDolly (P-51D)", "sender": "", "enemy": false, "mode": "" },
{ "id": 200, "msg": "=ARM14= ⋇Zagory (F2G-1) сбил NSSAG (Spitfire)", "sender": "", "enemy": false, "mode": "" },
{ "id": 201, "msg": "^OM2GD^ Old_Man1820 потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 202, "msg": "Old_Man1820td! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 203, "msg": "CaptainCaribou (Як-3) сбил =SKG10= FolyDolly (P-51D)", "sender": "", "enemy": false, "mode": "" },
{ "id": 204, "msg": "CaptainCaribou (Як-3) получил \"Спасатель истребителей\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 205, "msg": "=ARM14= ⋇Zagory (F2G-1) подбил Су-6 (АМ-42)", "sender": "", "enemy": false, "mode": "" },
{ "id": 206, "msg": "=SKG10= FolyDolly потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 207, "msg": "FolyDollytd! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 208, "msg": "=ARM14= ⋇Zagory (F2G-1) поджёг Су-6 (АМ-42)", "sender": "", "enemy": false, "mode": "" },
{ "id": 209, "msg": "NSSAG потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 210, "msg": "NSSAGtd! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 211, "msg": "⋇Lucid_Cribzz100 (A-26C) уничтожил ПВО", "sender": "", "enemy": false, "mode": "" },
{ "id": 212, "msg": "=ARM14= ⋇Zagory (F2G-1) уничтожил [ии] Су-6 (АМ-42)", "sender": "", "enemy": false, "mode": "" },
{ "id": 213, "msg": "=ARM14= ⋇Zagory (F2G-1) уничтожил Гаубица", "sender": "", "enemy": false, "mode": "" },
{ "id": 214, "msg": "=ARM14= ⋇Zagory (F2G-1) уничтожил ПВО", "sender": "", "enemy": false, "mode": "" },
{ "id": 215, "msg": "*MXG* fidler21 (F4U-4) подбил Су-6 (АМ-42)", "sender": "", "enemy": false, "mode": "" },
{ "id": 216, "msg": "*MXG* fidler21 (F4U-4) уничтожил [ии] Су-6 (АМ-42)", "sender": "", "enemy": false, "mode": "" },
{ "id": 217, "msg": ".SLY. Charliebl4kbeard (F4U-7) сбил ⋇echofour1 (P-51D)", "sender": "", "enemy": false, "mode": "" },
{ "id": 218, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) подбил ⋇Lucid_Cribzz100 (A-26C)", "sender": "", "enemy": false, "mode": "" },
{ "id": 219, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) сбил ⋇Lucid_Cribzz100 (A-26C)", "sender": "", "enemy": false, "mode": "" },
{ "id": 220, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) получил \"Спасатель наземной техники\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 221, "msg": "=ARM14= ⋇Zagory (F2G-1) уничтожил Гаубица", "sender": "", "enemy": false, "mode": "" },
{ "id": 222, "msg": "⋇Lucid_Cribzz100 потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 223, "msg": "⋇Lucid_Cribzz100td! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 224, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) подбил ⋇flameray7 (P-51D)", "sender": "", "enemy": false, "mode": "" },
{ "id": 225, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) поджёг ⋇flameray7 (P-51D)", "sender": "", "enemy": false, "mode": "" },
{ "id": 226, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) сбил ⋇flameray7 (P-51D)", "sender": "", "enemy": false, "mode": "" },
{ "id": 227, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) получил \"Двойной удар!\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 228, "msg": "⋇echofour1 потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 229, "msg": "⋇echofour1td! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 230, "msg": "CaptainCaribou (Як-3) поджёг =ARM14= ⋇Zagory (F2G-1)", "sender": "", "enemy": false, "mode": "" },
{ "id": 231, "msg": "⋇flameray7 потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 232, "msg": "⋇flameray7td! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 233, "msg": "CaptainCaribou (Як-3) сбил =ARM14= ⋇Zagory (F2G-1)", "sender": "", "enemy": false, "mode": "" },
{ "id": 234, "msg": "CaptainCaribou (Як-3) получил \"Спасатель наземной техники\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 235, "msg": "CaptainCaribou (Як-3) получил \"Ранг не имеет значения\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 236, "msg": "*MXG* fidler21 (F4U-4) подбил Су-6 (АМ-42)", "sender": "", "enemy": false, "mode": "" },
{ "id": 237, "msg": "*MXG* fidler21 (F4U-4) уничтожил [ии] Су-6 (АМ-42)", "sender": "", "enemy": false, "mode": "" },
{ "id": 238, "msg": "=D3S= De_Lucian (Як-9П) сбил Icantcraftthis (PB4Y-2)", "sender": "", "enemy": false, "mode": "" },
{ "id": 239, "msg": "=D3S= De_Lucian (Як-9П) получил \"Спасатель бомбардировщиков\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 240, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) подбил *MXG* fidler21 (F4U-4)", "sender": "", "enemy": false, "mode": "" },
{ "id": 241, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) сбил *MXG* fidler21 (F4U-4)", "sender": "", "enemy": false, "mode": "" },
{ "id": 242, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) получил \"Удар из тени: x3!\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 243, "msg": "Icantcraftthis потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 244, "msg": "Icantcraftthistd! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 245, "msg": "CaptainCaribou (Як-3) подбил Fw 190 F", "sender": "", "enemy": false, "mode": "" },
{ "id": 246, "msg": "Icantcraftthis (PB4Y-2) подбил =CMS= HornyTom (Ju 288 C)", "sender": "", "enemy": false, "mode": "" },
{ "id": 247, "msg": "CaptainCaribou (Як-3) уничтожил [ии] Fw 190 F", "sender": "", "enemy": false, "mode": "" },
{ "id": 248, "msg": ".SLY. Charliebl4kbeard (F4U-7) уничтожил Бронеавтомобиль", "sender": "", "enemy": false, "mode": "" },
{ "id": 249, "msg": ".SLY. Charliebl4kbeard (F4U-7) уничтожил Бронеавтомобиль", "sender": "", "enemy": false, "mode": "" },
{ "id": 250, "msg": "=ARM14= ⋇Zagory потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 251, "msg": "⋇Zagorytd! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 252, "msg": ".SLY. Charliebl4kbeard (F4U-7) уничтожил Бронеавтомобиль", "sender": "", "enemy": false, "mode": "" },
{ "id": 253, "msg": ".SLY. Charliebl4kbeard (F4U-7) уничтожил Бронеавтомобиль", "sender": "", "enemy": false, "mode": "" },
{ "id": 254, "msg": ".SLY. Charliebl4kbeard (F4U-7) уничтожил Бронеавтомобиль", "sender": "", "enemy": false, "mode": "" },
{ "id": 255, "msg": ".SLY. Charliebl4kbeard (F4U-7) уничтожил Бронеавтомобиль", "sender": "", "enemy": false, "mode": "" },
{ "id": 256, "msg": ".SLY. Charliebl4kbeard (F4U-7) получил \"Тройной удар!\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 257, "msg": "DJRAPPER995 (J2M5) подбил [TSBC] ⋇BerserkBranch65 (Spitfire)", "sender": "", "enemy": false, "mode": "" },
{ "id": 258, "msg": "DJRAPPER995 (J2M5) сбил [TSBC] ⋇BerserkBranch65 (Spitfire)", "sender": "", "enemy": false, "mode": "" },
{ "id": 259, "msg": "=CMS= HornyTom (Ju 288 C) совершил мягкую посадку", "sender": "", "enemy": false, "mode": "" },
{ "id": 260, "msg": ".SLY. Charliebl4kbeard (F4U-7) уничтожил Бронеавтомобиль", "sender": "", "enemy": false, "mode": "" },
{ "id": 261, "msg": ".SLY. Charliebl4kbeard (F4U-7) уничтожил Бронеавтомобиль", "sender": "", "enemy": false, "mode": "" },
{ "id": 262, "msg": "[TSBC] ⋇BerserkBranch65 потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 263, "msg": "⋇BerserkBranch65td! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 264, "msg": "DJRAPPER995 (J2M5) подбил =D3S= De_Lucian (Як-9П)", "sender": "", "enemy": false, "mode": "" },
{ "id": 265, "msg": "DJRAPPER995 (J2M5) поджёг =D3S= De_Lucian (Як-9П)", "sender": "", "enemy": false, "mode": "" },
{ "id": 266, "msg": "DJRAPPER995 (J2M5) сбил =D3S= De_Lucian (Як-9П)", "sender": "", "enemy": false, "mode": "" },
{ "id": 267, "msg": "=D3S= De_Lucian потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 268, "msg": "De_Luciantd! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 269, "msg": "=DRAKN= ⋇flavoredowl792 (F4U-4) подбил .SLY. Charliebl4kbeard (F4U-7)", "sender": "", "enemy": false, "mode": "" },
{ "id": 270, "msg": "DJRAPPER995 (J2M5) подбил .SLY. Charliebl4kbeard (F4U-7)", "sender": "", "enemy": false, "mode": "" },
{ "id": 271, "msg": "DJRAPPER995 (J2M5) сбил .SLY. Charliebl4kbeard (F4U-7)", "sender": "", "enemy": false, "mode": "" },
{ "id": 272, "msg": "=84CAR= ⋇willivp (AM-1) подбил CaptainCaribou (Як-3)", "sender": "", "enemy": false, "mode": "" },
{ "id": 273, "msg": "=84CAR= ⋇willivp (AM-1) сбил CaptainCaribou (Як-3)", "sender": "", "enemy": false, "mode": "" },
{ "id": 274, "msg": "CaptainCaribou потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 275, "msg": "CaptainCariboutd! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 276, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) сбил =84CAR= ⋇willivp (AM-1)", "sender": "", "enemy": false, "mode": "" },
{ "id": 277, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) поджёг =84CAR= ⋇willivp (AM-1)", "sender": "", "enemy": false, "mode": "" },
{ "id": 278, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) получил \"Мститель\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 279, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) получил \"Удар из тени: x4!\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 280, "msg": "=84CAR= ⋇willivp потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 281, "msg": "⋇willivptd! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 282, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) подбил =DRAKN= ⋇flavoredowl792 (F4U-4)", "sender": "", "enemy": false, "mode": "" },
{ "id": 283, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) поджёг =DRAKN= ⋇flavoredowl792 (F4U-4)", "sender": "", "enemy": false, "mode": "" },
{ "id": 284, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) сбил =DRAKN= ⋇flavoredowl792 (F4U-4)", "sender": "", "enemy": false, "mode": "" },
{ "id": 285, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) получил \"Профессионал: x5\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 286, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) получил \"Удар из тени: x5!\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 287, "msg": "DJRAPPER995 (J2M5) подбил ┾HuSp┿ johnnyredbeard (␗La-9)", "sender": "", "enemy": false, "mode": "" },
{ "id": 288, "msg": "=SP4CE= yipser (B-24D) подбил [SICH] _Strepsils_ (Me 264)", "sender": "", "enemy": false, "mode": "" },
{ "id": 289, "msg": "=DRAKN= ⋇flavoredowl792 потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 290, "msg": "⋇flavoredowl792td! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 291, "msg": "Вода перегрелась", "sender": "", "enemy": false, "mode": "" },
{ "id": 292, "msg": "Масло перегрелось", "sender": "", "enemy": false, "mode": "" },
{ "id": 293, "msg": "Вода перегрелась", "sender": "", "enemy": false, "mode": "" },
{ "id": 294, "msg": "Вода перегрелась", "sender": "", "enemy": false, "mode": "" },
{ "id": 295, "msg": "*MXG* fidler21 потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 296, "msg": "fidler21td! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 297, "msg": "Масло перегрелось", "sender": "", "enemy": false, "mode": "" },
{ "id": 298, "msg": "Вода перегрелась", "sender": "", "enemy": false, "mode": "" },
{ "id": 299, "msg": "Двигатель заглох: перегрев", "sender": "", "enemy": false, "mode": "" },
{ "id": 300, "msg": "[SICH] _Strepsils_ (Me 264) подбил =SP4CE= yipser (B-24D)", "sender": "", "enemy": false, "mode": "" },
{ "id": 301, "msg": "[SICH] _Strepsils_ (Me 264) поджёг =SP4CE= yipser (B-24D)", "sender": "", "enemy": false, "mode": "" },
{ "id": 302, "msg": "=CMS= HornyTom (Ju 288 C) уничтожил [ии] Fw 190 F", "sender": "", "enemy": false, "mode": "" },
{ "id": 303, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) подбил =SP4CE= yipser (B-24D)", "sender": "", "enemy": false, "mode": "" },
{ "id": 304, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) сбил =SP4CE= yipser (B-24D)", "sender": "", "enemy": false, "mode": "" },
{ "id": 305, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) получил \"Профессионал: x6\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 306, "msg": "=SP4CE= yipser потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 307, "msg": "yipsertd! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 308, "msg": "DJRAPPER995 (J2M5) подбил =CMS= HornyTom (Ju 288 C)", "sender": "", "enemy": false, "mode": "" },
{ "id": 309, "msg": "DJRAPPER995 (J2M5) поджёг =CMS= HornyTom (Ju 288 C)", "sender": "", "enemy": false, "mode": "" },
{ "id": 310, "msg": "DJRAPPER995 (J2M5) сбил =CMS= HornyTom (Ju 288 C)", "sender": "", "enemy": false, "mode": "" },
{ "id": 311, "msg": "=CMS= HornyTom потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 312, "msg": "HornyTomtd! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 313, "msg": "Несимметричный выпуск закрылков", "sender": "", "enemy": false, "mode": "" },
{ "id": 314, "msg": "DJRAPPER995 (J2M5) подбил Су-6 (АМ-42)", "sender": "", "enemy": false, "mode": "" },
{ "id": 315, "msg": "DJRAPPER995 (J2M5) уничтожил [ии] Су-6 (АМ-42)", "sender": "", "enemy": false, "mode": "" },
{ "id": 316, "msg": "DJRAPPER995 (J2M5) подбил Су-6 (АМ-42)", "sender": "", "enemy": false, "mode": "" },
{ "id": 317, "msg": "DJRAPPER995 (J2M5) уничтожил [ии] Су-6 (АМ-42)", "sender": "", "enemy": false, "mode": "" },
{ "id": 318, "msg": "[SICH] _Strepsils_ (Me 264) совершил мягкую посадку", "sender": "", "enemy": false, "mode": "" },
{ "id": 319, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) подбил DJRAPPER995 (J2M5)", "sender": "", "enemy": false, "mode": "" },
{ "id": 320, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) сбил DJRAPPER995 (J2M5)", "sender": "", "enemy": false, "mode": "" },
{ "id": 321, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) получил \"Спасатель истребителей\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 322, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) получил \"Мститель\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 323, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) получил \"Профессионал: x7\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 324, "msg": "CaptainCaribou (Як-3) получил \"Уравнитель\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 325, "msg": "⋇ OM2GD^ Catzo_ (Ту-2С) получил \"Громовержец\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 326, "msg": "=ARM14= ⋇Zagory (F2G-1) получил \"На подхвате\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 327, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) нанёс последний удар!", "sender": "", "enemy": false, "mode": "" },
{ "id": 328, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) получил \"Герой небес\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 329, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) получил \"Уцелевший\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 330, "msg": ".SLY. Charliebl4kbeard потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 331, "msg": "Charliebl4kbeardtd! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" }
]}