rawdata = {"events":[],
"damage":[
{ "id": 1, "msg": "⋇BlackLlama94 (B-17) подбил Як-9", "sender": "", "enemy": false, "mode": "" },
{ "id": 2, "msg": "⋇BlackLlama94 (B-17) уничтожил [ии] Як-9", "sender": "", "enemy": false, "mode": "" },
{ "id": 3, "msg": "Ricman99 (Tempest) подбил Toxer112 (Пе-8)", "sender": "", "enemy": false, "mode": "" },
{ "id": 4, "msg": "Ricman99 (Tempest) сбил Toxer112 (Пе-8)", "sender": "", "enemy": false, "mode": "" },
{ "id": 5, "msg": "Ricman99 (Tempest) поджёг Toxer112 (Пе-8)", "sender": "", "enemy": false, "mode": "" },
{ "id": 6, "msg": "Toxer112 (Пе-8) подбил Ricman99 (Tempest)", "sender": "", "enemy": false, "mode": "" },
{ "id": 7, "msg": "Toxer112 (И-185) сбил Ricman99 (Tempest)", "sender": "", "enemy": false, "mode": "" },
{ "id": 8, "msg": "Toxer112 (И-185) получил \"Око за око\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 9, "msg": "Ricman99 потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 10, "msg": "Ricman99td! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 11, "msg": "t72qok7ryw (Do 335 A) подбил Fw 190 F", "sender": "", "enemy": false, "mode": "" },
{ "id": 12, "msg": "t72qok7ryw (Do 335 A) уничтожил [ии] Fw 190 F", "sender": "", "enemy": false, "mode": "" },
{ "id": 13, "msg": "t72qok7ryw (Do 335 A) поджёг Fw 190 F", "sender": "", "enemy": false, "mode": "" },
{ "id": 14, "msg": "t72qok7ryw (Do 335 A) подбил Fw 190 F", "sender": "", "enemy": false, "mode": "" },
{ "id": 15, "msg": "t72qok7ryw (Do 335 A) уничтожил [ии] Fw 190 F", "sender": "", "enemy": false, "mode": "" },
{ "id": 16, "msg": "t72qok7ryw (Do 335 A) подбил Fw 190 F", "sender": "", "enemy": false, "mode": "" },
{ "id": 17, "msg": "t72qok7ryw (Do 335 A) подбил Fw 190 F", "sender": "", "enemy": false, "mode": "" },
{ "id": 18, "msg": "t72qok7ryw (Do 335 A) поджёг Fw 190 F", "sender": "", "enemy": false, "mode": "" },
{ "id": 19, "msg": "t72qok7ryw (Do 335 A) уничтожил [ии] Fw 190 F", "sender": "", "enemy": false, "mode": "" },
{ "id": 20, "msg": "t72qok7ryw (Do 335 A) подбил Fw 190 F", "sender": "", "enemy": false, "mode": "" },
{ "id": 21, "msg": "t72qok7ryw (Do 335 A) уничтожил [ии] Fw 190 F", "sender": "", "enemy": false, "mode": "" },
{ "id": 22, "msg": "t72qok7ryw (Do 335 A) подбил Fw 190 F", "sender": "", "enemy": false, "mode": "" },
{ "id": 23, "msg": "t72qok7ryw (Do 335 A) поджёг Fw 190 F", "sender": "", "enemy": false, "mode": "" },
{ "id": 24, "msg": "t72qok7ryw (Do 335 A) уничтожил [ии] Fw 190 F", "sender": "", "enemy": false, "mode": "" },
{ "id": 25, "msg": "Bf 109 G сбил t72qok7ryw (Do 335 A)", "sender": "", "enemy": false, "mode": "" },
{ "id": 26, "msg": "[SICH] _Strepsils_ (Me 264) уничтожил ПВО", "sender": "", "enemy": false, "mode": "" },
{ "id": 27, "msg": "⋇BlackLlama94 (B-17) подбил Toxer112 (И-185)", "sender": "", "enemy": false, "mode": "" },
{ "id": 28, "msg": "⋇BlackLlama94 (B-17) сбил Toxer112 (И-185)", "sender": "", "enemy": false, "mode": "" },
{ "id": 29, "msg": "Toxer112 (И-185) подбил ⋇BlackLlama94 (B-17)", "sender": "", "enemy": false, "mode": "" },
{ "id": 30, "msg": "Toxer112 потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 31, "msg": "Toxer112td! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 32, "msg": "t72qok7ryw потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 33, "msg": "t72qok7rywtd! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 34, "msg": "ponipolir (B-17) подбил QueMatracaAriel (▄Seafire Mk.III)", "sender": "", "enemy": false, "mode": "" },
{ "id": 35, "msg": "[SICH] _Strepsils_ (Me 264) подбил QueMatracaAriel (▄Seafire Mk.III)", "sender": "", "enemy": false, "mode": "" },
{ "id": 36, "msg": "[SICH] _Strepsils_ (Me 264) сбил QueMatracaAriel (▄Seafire Mk.III)", "sender": "", "enemy": false, "mode": "" },
{ "id": 37, "msg": "QueMatracaAriel потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 38, "msg": "QueMatracaArieltd! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 39, "msg": "Martini221 потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 40, "msg": "Martini221td! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 41, "msg": "mawipasopipas (B-25J) разбился", "sender": "", "enemy": false, "mode": "" },
{ "id": 42, "msg": "^PBAW^ ExtraMaksio21518 (Halifax B Mk.III) подбил Як-9", "sender": "", "enemy": false, "mode": "" },
{ "id": 43, "msg": "MassiveJuggs (PB4Y-2) уничтожил [ии] Fw 190 A", "sender": "", "enemy": false, "mode": "" },
{ "id": 44, "msg": "^PBAW^ ExtraMaksio21518 (Halifax B Mk.III) поджёг Як-9", "sender": "", "enemy": false, "mode": "" },
{ "id": 45, "msg": "^PBAW^ ExtraMaksio21518 (Halifax B Mk.III) уничтожил [ии] Як-9", "sender": "", "enemy": false, "mode": "" },
{ "id": 46, "msg": "⋇BlackLlama94 (B-17) разбился", "sender": "", "enemy": false, "mode": "" },
{ "id": 47, "msg": "⋇BlackLlama94 потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 48, "msg": "⋇BlackLlama94td! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 49, "msg": "^PBAW^ ExtraMaksio21518 (Halifax B Mk.III) разбился", "sender": "", "enemy": false, "mode": "" },
{ "id": 50, "msg": "^PBAW^ ExtraMaksio21518 потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 51, "msg": "ExtraMaksio21518td! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 52, "msg": "mawipasopipas (B-25J) разбился", "sender": "", "enemy": false, "mode": "" },
{ "id": 53, "msg": "MassiveJuggs (PB4Y-2) подбил Bf 109 G", "sender": "", "enemy": false, "mode": "" },
{ "id": 54, "msg": "MassiveJuggs (PB4Y-2) разбился", "sender": "", "enemy": false, "mode": "" },
{ "id": 55, "msg": "ponipolir (B-17) подбил Bf 109 G", "sender": "", "enemy": false, "mode": "" },
{ "id": 56, "msg": "ponipolir (B-17) уничтожил [ии] Bf 109 G", "sender": "", "enemy": false, "mode": "" },
{ "id": 57, "msg": "jilas13 (B-17G) подбил Fw 190 A", "sender": "", "enemy": false, "mode": "" },
{ "id": 58, "msg": "jilas13 (B-17G) уничтожил [ии] Fw 190 A", "sender": "", "enemy": false, "mode": "" },
{ "id": 59, "msg": "mawipasopipas (B-25J) разбился", "sender": "", "enemy": false, "mode": "" },
{ "id": 60, "msg": "MassiveJuggs (PB4Y-2) уничтожил leKPz M41", "sender": "", "enemy": false, "mode": "" },
{ "id": 61, "msg": "Adas7734 (AM-1) разбился", "sender": "", "enemy": false, "mode": "" },
{ "id": 62, "msg": "Adas7734 потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 63, "msg": "Adas7734td! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 64, "msg": "⋇fire_storm_glt (▄AD-4) подбил jilas13 (B-17G)", "sender": "", "enemy": false, "mode": "" },
{ "id": 65, "msg": "jilas13 (B-17G) сбил ⋇fire_storm_glt (▄AD-4)", "sender": "", "enemy": false, "mode": "" },
{ "id": 66, "msg": "⋇fire_storm_glt (▄AD-4) сбил jilas13 (B-17G)", "sender": "", "enemy": false, "mode": "" },
{ "id": 67, "msg": "RawbonedInnovatr потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 68, "msg": "RawbonedInnovatrtd! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 69, "msg": "mawipasopipas (B-25J) разбился", "sender": "", "enemy": false, "mode": "" },
{ "id": 70, "msg": "⋇fire_storm_glt (▄AD-4) уничтожил ЗСУ-37", "sender": "", "enemy": false, "mode": "" },
{ "id": 71, "msg": "ponipolir (B-17) подбил Fw 190 A", "sender": "", "enemy": false, "mode": "" },
{ "id": 72, "msg": "ponipolir (B-17) поджёг Fw 190 A", "sender": "", "enemy": false, "mode": "" },
{ "id": 73, "msg": "ponipolir (B-17) уничтожил [ии] Fw 190 A", "sender": "", "enemy": false, "mode": "" },
{ "id": 74, "msg": "⋇fire_storm_glt (▄AD-4) уничтожил БМП-1", "sender": "", "enemy": false, "mode": "" },
{ "id": 75, "msg": "MassiveJuggs (PB4Y-2) уничтожил [ии] Bf 109 G", "sender": "", "enemy": false, "mode": "" },
{ "id": 76, "msg": "jilas13 (B-17G) получил \"Серия захватов: x2!\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 77, "msg": "UA_GO_PROSHEN (AM-1) разбился", "sender": "", "enemy": false, "mode": "" },
{ "id": 78, "msg": "UA_GO_PROSHEN потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 79, "msg": "UA_GO_PROSHENtd! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 80, "msg": "Вода перегрелась", "sender": "", "enemy": false, "mode": "" },
{ "id": 81, "msg": "Масло перегрелось", "sender": "", "enemy": false, "mode": "" },
{ "id": 82, "msg": "Вода перегрелась", "sender": "", "enemy": false, "mode": "" },
{ "id": 83, "msg": "Масло перегрелось", "sender": "", "enemy": false, "mode": "" },
{ "id": 84, "msg": "Вода перегрелась", "sender": "", "enemy": false, "mode": "" },
{ "id": 85, "msg": "Масло перегрелось", "sender": "", "enemy": false, "mode": "" },
{ "id": 86, "msg": "Вода перегрелась", "sender": "", "enemy": false, "mode": "" },
{ "id": 87, "msg": "Масло перегрелось", "sender": "", "enemy": false, "mode": "" },
{ "id": 88, "msg": "jilas13 (B-17G) подбил ⋇fire_storm_glt (▄AD-4)", "sender": "", "enemy": false, "mode": "" },
{ "id": 89, "msg": "⋇fire_storm_glt (▄AD-4) подбил jilas13 (B-17G)", "sender": "", "enemy": false, "mode": "" },
{ "id": 90, "msg": "Двигатель заглох: перегрев", "sender": "", "enemy": false, "mode": "" },
{ "id": 91, "msg": "Двигатель заглох: перегрев", "sender": "", "enemy": false, "mode": "" },
{ "id": 92, "msg": "Двигатель заглох: перегрев", "sender": "", "enemy": false, "mode": "" },
{ "id": 93, "msg": "Двигатель заглох: перегрев", "sender": "", "enemy": false, "mode": "" },
{ "id": 94, "msg": "jilas13 (B-17G) сбил ⋇fire_storm_glt (▄AD-4)", "sender": "", "enemy": false, "mode": "" }
]}

{"events":[

],
"damage":[
{ "id": 193, "msg": "*MXG* fidler21 (F4U-4) подбил ^OM2GD^ Catzo_ (Ту-2С)", "sender": "", "enemy": false, "mode": "" },
{ "id": 194, "msg": "*MXG* fidler21 (F4U-4) сбил ^OM2GD^ Catzo_ (Ту-2С)", "sender": "", "enemy": false, "mode": "" },
{ "id": 195, "msg": "*MXG* fidler21 (F4U-4) сбил ^OM2GD^ Old_Man1820 (Fw 190 F)", "sender": "", "enemy": false, "mode": "" },
{ "id": 196, "msg": "⋇Lucid_Cribzz100 (A-26C) уничтожил Гаубица", "sender": "", "enemy": false, "mode": "" },
{ "id": 197, "msg": "^OM2GD^ Catzo_ потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 198, "msg": "Catzo_td! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 199, "msg": "CaptainCaribou (Як-3) поджёг =SKG10= FolyDolly (P-51D)", "sender": "", "enemy": false, "mode": "" },
{ "id": 200, "msg": "=ARM14= ⋇Zagory (F2G-1) сбил NSSAG (Spitfire)", "sender": "", "enemy": false, "mode": "" },
{ "id": 201, "msg": "^OM2GD^ Old_Man1820 потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 202, "msg": "Old_Man1820td! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 203, "msg": "CaptainCaribou (Як-3) сбил =SKG10= FolyDolly (P-51D)", "sender": "", "enemy": false, "mode": "" },
{ "id": 204, "msg": "CaptainCaribou (Як-3) получил \"Спасатель истребителей\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 205, "msg": "=ARM14= ⋇Zagory (F2G-1) подбил Су-6 (АМ-42)", "sender": "", "enemy": false, "mode": "" },
{ "id": 206, "msg": "=SKG10= FolyDolly потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 207, "msg": "FolyDollytd! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 208, "msg": "=ARM14= ⋇Zagory (F2G-1) поджёг Су-6 (АМ-42)", "sender": "", "enemy": false, "mode": "" },
{ "id": 209, "msg": "NSSAG потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 210, "msg": "NSSAGtd! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 211, "msg": "⋇Lucid_Cribzz100 (A-26C) уничтожил ПВО", "sender": "", "enemy": false, "mode": "" },
{ "id": 212, "msg": "=ARM14= ⋇Zagory (F2G-1) уничтожил [ии] Су-6 (АМ-42)", "sender": "", "enemy": false, "mode": "" },
{ "id": 213, "msg": "=ARM14= ⋇Zagory (F2G-1) уничтожил Гаубица", "sender": "", "enemy": false, "mode": "" },
{ "id": 214, "msg": "=ARM14= ⋇Zagory (F2G-1) уничтожил ПВО", "sender": "", "enemy": false, "mode": "" },
{ "id": 215, "msg": "*MXG* fidler21 (F4U-4) подбил Су-6 (АМ-42)", "sender": "", "enemy": false, "mode": "" },
{ "id": 216, "msg": "*MXG* fidler21 (F4U-4) уничтожил [ии] Су-6 (АМ-42)", "sender": "", "enemy": false, "mode": "" },
{ "id": 217, "msg": ".SLY. Charliebl4kbeard (F4U-7) сбил ⋇echofour1 (P-51D)", "sender": "", "enemy": false, "mode": "" },
{ "id": 218, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) подбил ⋇Lucid_Cribzz100 (A-26C)", "sender": "", "enemy": false, "mode": "" },
{ "id": 219, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) сбил ⋇Lucid_Cribzz100 (A-26C)", "sender": "", "enemy": false, "mode": "" },
{ "id": 220, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) получил \"Спасатель наземной техники\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 221, "msg": "=ARM14= ⋇Zagory (F2G-1) уничтожил Гаубица", "sender": "", "enemy": false, "mode": "" },
{ "id": 222, "msg": "⋇Lucid_Cribzz100 потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 223, "msg": "⋇Lucid_Cribzz100td! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 224, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) подбил ⋇flameray7 (P-51D)", "sender": "", "enemy": false, "mode": "" },
{ "id": 225, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) поджёг ⋇flameray7 (P-51D)", "sender": "", "enemy": false, "mode": "" },
{ "id": 226, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) сбил ⋇flameray7 (P-51D)", "sender": "", "enemy": false, "mode": "" },
{ "id": 227, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) получил \"Двойной удар!\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 228, "msg": "⋇echofour1 потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 229, "msg": "⋇echofour1td! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 230, "msg": "CaptainCaribou (Як-3) поджёг =ARM14= ⋇Zagory (F2G-1)", "sender": "", "enemy": false, "mode": "" },
{ "id": 231, "msg": "⋇flameray7 потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 232, "msg": "⋇flameray7td! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 233, "msg": "CaptainCaribou (Як-3) сбил =ARM14= ⋇Zagory (F2G-1)", "sender": "", "enemy": false, "mode": "" },
{ "id": 234, "msg": "CaptainCaribou (Як-3) получил \"Спасатель наземной техники\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 235, "msg": "CaptainCaribou (Як-3) получил \"Ранг не имеет значения\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 236, "msg": "*MXG* fidler21 (F4U-4) подбил Су-6 (АМ-42)", "sender": "", "enemy": false, "mode": "" },
{ "id": 237, "msg": "*MXG* fidler21 (F4U-4) уничтожил [ии] Су-6 (АМ-42)", "sender": "", "enemy": false, "mode": "" },
{ "id": 238, "msg": "=D3S= De_Lucian (Як-9П) сбил Icantcraftthis (PB4Y-2)", "sender": "", "enemy": false, "mode": "" },
{ "id": 239, "msg": "=D3S= De_Lucian (Як-9П) получил \"Спасатель бомбардировщиков\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 240, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) подбил *MXG* fidler21 (F4U-4)", "sender": "", "enemy": false, "mode": "" },
{ "id": 241, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) сбил *MXG* fidler21 (F4U-4)", "sender": "", "enemy": false, "mode": "" },
{ "id": 242, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) получил \"Удар из тени: x3!\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 243, "msg": "Icantcraftthis потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 244, "msg": "Icantcraftthistd! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 245, "msg": "CaptainCaribou (Як-3) подбил Fw 190 F", "sender": "", "enemy": false, "mode": "" },
{ "id": 246, "msg": "Icantcraftthis (PB4Y-2) подбил =CMS= HornyTom (Ju 288 C)", "sender": "", "enemy": false, "mode": "" },
{ "id": 247, "msg": "CaptainCaribou (Як-3) уничтожил [ии] Fw 190 F", "sender": "", "enemy": false, "mode": "" },
{ "id": 248, "msg": ".SLY. Charliebl4kbeard (F4U-7) уничтожил Бронеавтомобиль", "sender": "", "enemy": false, "mode": "" },
{ "id": 249, "msg": ".SLY. Charliebl4kbeard (F4U-7) уничтожил Бронеавтомобиль", "sender": "", "enemy": false, "mode": "" },
{ "id": 250, "msg": "=ARM14= ⋇Zagory потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 251, "msg": "⋇Zagorytd! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 252, "msg": ".SLY. Charliebl4kbeard (F4U-7) уничтожил Бронеавтомобиль", "sender": "", "enemy": false, "mode": "" },
{ "id": 253, "msg": ".SLY. Charliebl4kbeard (F4U-7) уничтожил Бронеавтомобиль", "sender": "", "enemy": false, "mode": "" },
{ "id": 254, "msg": ".SLY. Charliebl4kbeard (F4U-7) уничтожил Бронеавтомобиль", "sender": "", "enemy": false, "mode": "" },
{ "id": 255, "msg": ".SLY. Charliebl4kbeard (F4U-7) уничтожил Бронеавтомобиль", "sender": "", "enemy": false, "mode": "" },
{ "id": 256, "msg": ".SLY. Charliebl4kbeard (F4U-7) получил \"Тройной удар!\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 257, "msg": "DJRAPPER995 (J2M5) подбил [TSBC] ⋇BerserkBranch65 (Spitfire)", "sender": "", "enemy": false, "mode": "" },
{ "id": 258, "msg": "DJRAPPER995 (J2M5) сбил [TSBC] ⋇BerserkBranch65 (Spitfire)", "sender": "", "enemy": false, "mode": "" },
{ "id": 259, "msg": "=CMS= HornyTom (Ju 288 C) совершил мягкую посадку", "sender": "", "enemy": false, "mode": "" },
{ "id": 260, "msg": ".SLY. Charliebl4kbeard (F4U-7) уничтожил Бронеавтомобиль", "sender": "", "enemy": false, "mode": "" },
{ "id": 261, "msg": ".SLY. Charliebl4kbeard (F4U-7) уничтожил Бронеавтомобиль", "sender": "", "enemy": false, "mode": "" },
{ "id": 262, "msg": "[TSBC] ⋇BerserkBranch65 потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 263, "msg": "⋇BerserkBranch65td! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 264, "msg": "DJRAPPER995 (J2M5) подбил =D3S= De_Lucian (Як-9П)", "sender": "", "enemy": false, "mode": "" },
{ "id": 265, "msg": "DJRAPPER995 (J2M5) поджёг =D3S= De_Lucian (Як-9П)", "sender": "", "enemy": false, "mode": "" },
{ "id": 266, "msg": "DJRAPPER995 (J2M5) сбил =D3S= De_Lucian (Як-9П)", "sender": "", "enemy": false, "mode": "" },
{ "id": 267, "msg": "=D3S= De_Lucian потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 268, "msg": "De_Luciantd! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 269, "msg": "=DRAKN= ⋇flavoredowl792 (F4U-4) подбил .SLY. Charliebl4kbeard (F4U-7)", "sender": "", "enemy": false, "mode": "" },
{ "id": 270, "msg": "DJRAPPER995 (J2M5) подбил .SLY. Charliebl4kbeard (F4U-7)", "sender": "", "enemy": false, "mode": "" },
{ "id": 271, "msg": "DJRAPPER995 (J2M5) сбил .SLY. Charliebl4kbeard (F4U-7)", "sender": "", "enemy": false, "mode": "" },
{ "id": 272, "msg": "=84CAR= ⋇willivp (AM-1) подбил CaptainCaribou (Як-3)", "sender": "", "enemy": false, "mode": "" },
{ "id": 273, "msg": "=84CAR= ⋇willivp (AM-1) сбил CaptainCaribou (Як-3)", "sender": "", "enemy": false, "mode": "" },
{ "id": 274, "msg": "CaptainCaribou потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 275, "msg": "CaptainCariboutd! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 276, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) сбил =84CAR= ⋇willivp (AM-1)", "sender": "", "enemy": false, "mode": "" },
{ "id": 277, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) поджёг =84CAR= ⋇willivp (AM-1)", "sender": "", "enemy": false, "mode": "" },
{ "id": 278, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) получил \"Мститель\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 279, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) получил \"Удар из тени: x4!\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 280, "msg": "=84CAR= ⋇willivp потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 281, "msg": "⋇willivptd! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 282, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) подбил =DRAKN= ⋇flavoredowl792 (F4U-4)", "sender": "", "enemy": false, "mode": "" },
{ "id": 283, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) поджёг =DRAKN= ⋇flavoredowl792 (F4U-4)", "sender": "", "enemy": false, "mode": "" },
{ "id": 284, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) сбил =DRAKN= ⋇flavoredowl792 (F4U-4)", "sender": "", "enemy": false, "mode": "" },
{ "id": 285, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) получил \"Профессионал: x5\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 286, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) получил \"Удар из тени: x5!\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 287, "msg": "DJRAPPER995 (J2M5) подбил ┾HuSp┿ johnnyredbeard (␗La-9)", "sender": "", "enemy": false, "mode": "" },
{ "id": 288, "msg": "=SP4CE= yipser (B-24D) подбил [SICH] _Strepsils_ (Me 264)", "sender": "", "enemy": false, "mode": "" },
{ "id": 289, "msg": "=DRAKN= ⋇flavoredowl792 потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 290, "msg": "⋇flavoredowl792td! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 291, "msg": "Вода перегрелась", "sender": "", "enemy": false, "mode": "" },
{ "id": 292, "msg": "Масло перегрелось", "sender": "", "enemy": false, "mode": "" },
{ "id": 293, "msg": "Вода перегрелась", "sender": "", "enemy": false, "mode": "" },
{ "id": 294, "msg": "Вода перегрелась", "sender": "", "enemy": false, "mode": "" },
{ "id": 295, "msg": "*MXG* fidler21 потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 296, "msg": "fidler21td! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 297, "msg": "Масло перегрелось", "sender": "", "enemy": false, "mode": "" },
{ "id": 298, "msg": "Вода перегрелась", "sender": "", "enemy": false, "mode": "" },
{ "id": 299, "msg": "Двигатель заглох: перегрев", "sender": "", "enemy": false, "mode": "" },
{ "id": 300, "msg": "[SICH] _Strepsils_ (Me 264) подбил =SP4CE= yipser (B-24D)", "sender": "", "enemy": false, "mode": "" },
{ "id": 301, "msg": "[SICH] _Strepsils_ (Me 264) поджёг =SP4CE= yipser (B-24D)", "sender": "", "enemy": false, "mode": "" },
{ "id": 302, "msg": "=CMS= HornyTom (Ju 288 C) уничтожил [ии] Fw 190 F", "sender": "", "enemy": false, "mode": "" },
{ "id": 303, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) подбил =SP4CE= yipser (B-24D)", "sender": "", "enemy": false, "mode": "" },
{ "id": 304, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) сбил =SP4CE= yipser (B-24D)", "sender": "", "enemy": false, "mode": "" },
{ "id": 305, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) получил \"Профессионал: x6\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 306, "msg": "=SP4CE= yipser потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 307, "msg": "yipsertd! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 308, "msg": "DJRAPPER995 (J2M5) подбил =CMS= HornyTom (Ju 288 C)", "sender": "", "enemy": false, "mode": "" },
{ "id": 309, "msg": "DJRAPPER995 (J2M5) поджёг =CMS= HornyTom (Ju 288 C)", "sender": "", "enemy": false, "mode": "" },
{ "id": 310, "msg": "DJRAPPER995 (J2M5) сбил =CMS= HornyTom (Ju 288 C)", "sender": "", "enemy": false, "mode": "" },
{ "id": 311, "msg": "=CMS= HornyTom потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 312, "msg": "HornyTomtd! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" },
{ "id": 313, "msg": "Несимметричный выпуск закрылков", "sender": "", "enemy": false, "mode": "" },
{ "id": 314, "msg": "DJRAPPER995 (J2M5) подбил Су-6 (АМ-42)", "sender": "", "enemy": false, "mode": "" },
{ "id": 315, "msg": "DJRAPPER995 (J2M5) уничтожил [ии] Су-6 (АМ-42)", "sender": "", "enemy": false, "mode": "" },
{ "id": 316, "msg": "DJRAPPER995 (J2M5) подбил Су-6 (АМ-42)", "sender": "", "enemy": false, "mode": "" },
{ "id": 317, "msg": "DJRAPPER995 (J2M5) уничтожил [ии] Су-6 (АМ-42)", "sender": "", "enemy": false, "mode": "" },
{ "id": 318, "msg": "[SICH] _Strepsils_ (Me 264) совершил мягкую посадку", "sender": "", "enemy": false, "mode": "" },
{ "id": 319, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) подбил DJRAPPER995 (J2M5)", "sender": "", "enemy": false, "mode": "" },
{ "id": 320, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) сбил DJRAPPER995 (J2M5)", "sender": "", "enemy": false, "mode": "" },
{ "id": 321, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) получил \"Спасатель истребителей\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 322, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) получил \"Мститель\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 323, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) получил \"Профессионал: x7\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 324, "msg": "CaptainCaribou (Як-3) получил \"Уравнитель\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 325, "msg": "⋇ OM2GD^ Catzo_ (Ту-2С) получил \"Громовержец\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 326, "msg": "=ARM14= ⋇Zagory (F2G-1) получил \"На подхвате\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 327, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) нанёс последний удар!", "sender": "", "enemy": false, "mode": "" },
{ "id": 328, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) получил \"Герой небес\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 329, "msg": "┾HuSp┿ johnnyredbeard (␗La-9) получил \"Уцелевший\"", "sender": "", "enemy": false, "mode": "" },
{ "id": 330, "msg": ".SLY. Charliebl4kbeard потерял связь", "sender": "", "enemy": false, "mode": "" },
{ "id": 331, "msg": "Charliebl4kbeardtd! kd?NET_PLAYER_DISCONNECT_FROM_GAME", "sender": "", "enemy": false, "mode": "" }
]}